name: Scrape locations

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  scrape_locations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Expose API secret to workflow
        run: |
          GOOGLE_MAPS_API_KEY="${{ secrets.GOOGLE_MAPS_API_KEY }}"
          echo "GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY" >> "$GITHUB_ENV"

      - name: Restore address cache
        uses: actions/cache@v6
        with:
          path: scraper/address_cache.json
          key: address-cache-restore-${{ github.run_id }}
          restore-keys: |
            address-cache-restore-

      - name: Scrape locations
        run: pip install -r scraper/requirements.txt && bash scraper/run.sh

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.DEPLOYER_BOT_KEY }}"
          projectId: veradas-terkep
          channelId: live
